### ISSUE TITLE
[PE-D] App Startup Page's Sample Data Looks 'Broken'

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-1/tp#129]
When starting the app, the sample data seems to have been corrupted as it is different from the one shown in the User Guide and this may cause users to be confused when seeing such corrupted data. 
![App Startup Sample Data.png](https://raw.githubusercontent.com/joey-chance/ped/main/files/c2b9db09-8687-4a4f-803d-18600ef8b076.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: joey-chance/ped#2

**Comment by louisdavinlie** [comment]
Duplicate of #132
