### ISSUE TITLE
[PE-D] Data File

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-1/tp#130]
The location of the data file is incorrectly reported in the UG. This also means that the data file could not be located for external editing. 

![image.png](https://raw.githubusercontent.com/thewrik/ped/main/files/9f2d5505-1c22-4550-a61c-f0d13813cee2.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: thewrik/ped#2

**Comment by lzf834** [comment]
Team couldn't replicate. Team members have tried running on Mac/Apple, no issues on our end. Not enough information.
