### ISSUE TITLE
[PE-D] Corrupted UI Text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-1/tp#132]
There seems to be an error in displaying the data as even newly added data seems to output corrupted text.
![Corrupted UI.png](https://raw.githubusercontent.com/joey-chance/ped/main/files/b5d0bb8a-e829-41ec-8cbc-28506bb06590.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: joey-chance/ped#3

**Comment by lzf834** [comment]
Font issue in css file. Change to arial font
