### ISSUE TITLE
Basic Features - Add Status class to Person package

### ISSUE THREAD

**Issue by lzf834** [AY2122S2-CS2103T-T12-1/tp#31]
Add Status class to each Person

**Comment by Fenway17** [comment]
Collaborator: Zi Foong
Implemented:
1. Status Class

Edits:
1. ui/PersonCard.java - DONE
2. Storage/JsonAdaptedPerson.java - DONE
3. logic/commands/AddCommand.java - DONE
4. logic/parser/AddCommandParser.java - DONE
5. logic/parser/CliSyntax.java - DONE
6. logic/parser/parserUtil.java - DONE
7. model/person/Person.java - DONE
8. logic/commands/EditCommand.java - DONE
9. parser/EditCommandParser.java - DONE

test folder
1. testutil/PersonBuilder.java - DONE
2. test/JsonAdaptedPersonTest.java - DONE

resources folder
1. PersonListCard.fxml - DONE

SampleData/Test changes:
1. model/util/SampleDataUtil.java - DONE
